export const COUNTRY_CODES = [
  { name: 'TURKEY', value: '+90', code: 'TR', nationalPattern: '^5\\d{9}$' },
  { name: 'ALBANIA', value: '+355', code: 'AL', nationalPattern: '^\\d{7,9}$' },
  { name: 'ARMENIA', value: '+374', code: 'AM', nationalPattern: '^\\d{8}$' },
  { name: 'AZERBAIJAN', value: '+994', code: 'AZ', nationalPattern: '^\\d{9}$' },
  { name: 'BULGARIA', value: '+359', code: 'BG', nationalPattern: '^\\d{8,9}$' },
  { name: 'CYPRUS', value: '+357', code: 'CY', nationalPattern: '^\\d{8}$' },
  { name: 'EGYPT', value: '+20', code: 'EG', nationalPattern: '^\\d{10}$' },
  { name: 'FRANCE', value: '+33', code: 'FR', nationalPattern: '^\\d{9}$' },
  { name: 'GEORGIA', value: '+995', code: 'GE', nationalPattern: '^\\d{9}$' },
  { name: 'GERMANY', value: '+49', code: 'DE', nationalPattern: '^\\d{7,13}$' },
  { name: 'GREECE', value: '+30', code: 'GR', nationalPattern: '^\\d{10}$' },
  { name: 'IRAN', value: '+98', code: 'IR', nationalPattern: '^\\d{10}$' },
  { name: 'IRAQ', value: '+964', code: 'IQ', nationalPattern: '^\\d{10}$' },
  { name: 'ISRAEL', value: '+972', code: 'IL', nationalPattern: '^\\d{9}$' },
  { name: 'JORDAN', value: '+962', code: 'JO', nationalPattern: '^\\d{9}$' },
  { name: 'KAZAKHSTAN', value: '+7', code: 'KZ', nationalPattern: '^\\d{10}$' },
  { name: 'KYRGYZSTAN', value: '+996', code: 'KG', nationalPattern: '^\\d{9}$' },
  { name: 'LEBANON', value: '+961', code: 'LB', nationalPattern: '^\\d{8}$' },
  { name: 'NETHERLANDS', value: '+31', code: 'NL', nationalPattern: '^\\d{9}$' },
  { name: 'NORTH_MACEDONIA', value: '+389', code: 'MK', nationalPattern: '^\\d{8}$' },
  { name: 'ROMANIA', value: '+40', code: 'RO', nationalPattern: '^\\d{9}$' },
  { name: 'RUSSIA', value: '+7', code: 'RU', nationalPattern: '^\\d{10}$' },
  { name: 'SERBIA', value: '+381', code: 'RS', nationalPattern: '^\\d{8,9}$' },
  { name: 'SYRIA', value: '+963', code: 'SY', nationalPattern: '^\\d{9}$' },
  { name: 'TAJIKISTAN', value: '+992', code: 'TJ', nationalPattern: '^\\d{9}$' },
  { name: 'TURKMENISTAN', value: '+993', code: 'TM', nationalPattern: '^\\d{8}$' },
  { name: 'UKRAINE', value: '+380', code: 'UA', nationalPattern: '^\\d{9}$' },
  { name: 'UNITED_KINGDOM', value: '+44', code: 'GB', nationalPattern: '^\\d{10}$' },
  { name: 'USA', value: '+1', code: 'US', nationalPattern: '^\\d{10}$' },
  { name: 'UZBEKISTAN', value: '+998', code: 'UZ', nationalPattern: '^\\d{9}$' },
];

export const DEFAULT_COUNTRY_CODE = '+90';
